name: 'Terraform Plan'

on:
  workflow_dispatch:
  
env:
  TF_VAR_credentials: ${{ secrets.TF_VAR_CREDENTIALS }}
  TF_VAR_DB_HOST: ${{ secrets.TF_VAR_DB_HOST }}
  TF_VAR_DB_PASS: ${{ secrets.TF_VAR_DB_PASS }}
  TF_VAR_DB_USER: ${{ secrets.TF_VAR_DB_USER }}
    
permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v3


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7
        
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.TF_VAR_CREDENTIALS }}'
        

    - name: Terraform Init
      working-directory: terraform
      run: terraform init
      

    - id: plan
      working-directory: terraform
      run: terraform plan -input=false

